"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
sys.path.insert(1, '../src')
from SwitchBox import *

APP = ['../src/SwitchBox.py']
DATA_FILES = []
OPTIONS = {'iconfile': '../src/assets/SwitchBox.icns',
           'plist':{
           'CFBundleGetInfoString' : 'MIDI Re-routing Program',
           'CFBundleIdentifier' : 'jiaweichen.switchbox',
           'CFBundleName': 'SwitchBox',
           'CFBundleDisplayName': 'SwitchBox',
           'CFBundleVersion': '{} "{}"'.format(VER_STRING, VER_NAME),
           'CFBundleShortVersionString': str(VER_STRING),
           'NSHumanReadableCopyright': "Copyright (c) 2019 Jiawei Chen"},
           'resources':["../src/assets"]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
